"""Add KnowledgeArticle model

Revision ID: 11f2ec2d69bf
Revises: 43c661b4beab
Create Date: 2026-03-06 13:26:45.570598
"""
from alembic import op
import sqlalchemy as sa


revision = '11f2ec2d69bf'
down_revision = '43c661b4beab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_article',
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('article_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_article_article_number'), 'knowledge_article', ['article_number'], unique=True)
    op.create_index(op.f('ix_knowledge_article_category'), 'knowledge_article', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_article_chapter_id'), 'knowledge_article', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_knowledge_article_organization_id'), 'knowledge_article', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_article_scope'), 'knowledge_article', ['scope'], unique=False)
    op.create_index(op.f('ix_knowledge_article_status'), 'knowledge_article', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_article_status'), table_name='knowledge_article')
    op.drop_index(op.f('ix_knowledge_article_scope'), table_name='knowledge_article')
    op.drop_index(op.f('ix_knowledge_article_organization_id'), table_name='knowledge_article')
    op.drop_index(op.f('ix_knowledge_article_chapter_id'), table_name='knowledge_article')
    op.drop_index(op.f('ix_knowledge_article_category'), table_name='knowledge_article')
    op.drop_index(op.f('ix_knowledge_article_article_number'), table_name='knowledge_article')
    op.drop_table('knowledge_article')
    # ### end Alembic commands ###
