"""Add Invoice model for chapter and regional invoicing

Revision ID: 172b38581b4c
Revises: 11f2ec2d69bf
Create Date: 2026-03-20 12:17:40.796434
"""
from alembic import op
import sqlalchemy as sa


revision = '172b38581b4c'
down_revision = '11f2ec2d69bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('billed_user_id', sa.String(length=36), nullable=True),
    sa.Column('fee_type_id', sa.String(length=50), nullable=True),
    sa.Column('region_id', sa.String(length=36), nullable=True),
    sa.Column('billed_chapter_id', sa.String(length=36), nullable=True),
    sa.Column('per_member_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billed_chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['billed_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_billed_chapter_id'), 'invoice', ['billed_chapter_id'], unique=False)
    op.create_index(op.f('ix_invoice_billed_user_id'), 'invoice', ['billed_user_id'], unique=False)
    op.create_index(op.f('ix_invoice_chapter_id'), 'invoice', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_invoice_invoice_number'), 'invoice', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoice_region_id'), 'invoice', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_region_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_invoice_number'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_chapter_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_billed_user_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_billed_chapter_id'), table_name='invoice')
    op.drop_table('invoice')
    # ### end Alembic commands ###
