"""add_workflow_tables

Revision ID: 2b682d2188c6
Revises: baa7d737e920
Create Date: 2026-02-18 19:25:09.685073
"""
from alembic import op
import sqlalchemy as sa


revision = '2b682d2188c6'
down_revision = 'baa7d737e920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_template',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('completion_actions', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_template_chapter_id'), 'workflow_template', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_workflow_template_organization_id'), 'workflow_template', ['organization_id'], unique=False)
    op.create_table('workflow_instance',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('initiated_by', sa.String(length=36), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instance_chapter_id'), 'workflow_instance', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_workflow_instance_template_id'), 'workflow_instance', ['template_id'], unique=False)
    op.create_table('workflow_step',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parallel_group', sa.String(length=100), nullable=True),
    sa.Column('approver_type', sa.String(length=20), nullable=False),
    sa.Column('approver_role', sa.String(length=30), nullable=True),
    sa.Column('approver_user_id', sa.String(length=36), nullable=True),
    sa.Column('condition_json', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_step_template_id'), 'workflow_step', ['template_id'], unique=False)
    op.create_table('workflow_step_instance',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to_role', sa.String(length=30), nullable=True),
    sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True),
    sa.Column('action_taken_by', sa.String(length=36), nullable=True),
    sa.Column('action_taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_taken_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instance.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_step_instance_instance_id'), 'workflow_step_instance', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflow_step_instance_step_id'), 'workflow_step_instance', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_step_instance_step_id'), table_name='workflow_step_instance')
    op.drop_index(op.f('ix_workflow_step_instance_instance_id'), table_name='workflow_step_instance')
    op.drop_table('workflow_step_instance')
    op.drop_index(op.f('ix_workflow_step_template_id'), table_name='workflow_step')
    op.drop_table('workflow_step')
    op.drop_index(op.f('ix_workflow_instance_template_id'), table_name='workflow_instance')
    op.drop_index(op.f('ix_workflow_instance_chapter_id'), table_name='workflow_instance')
    op.drop_table('workflow_instance')
    op.drop_index(op.f('ix_workflow_template_organization_id'), table_name='workflow_template')
    op.drop_index(op.f('ix_workflow_template_chapter_id'), table_name='workflow_template')
    op.drop_table('workflow_template')
    # ### end Alembic commands ###
