"""Add ChapterTransferRequest model

Revision ID: 3bab8cc55439
Revises: 8d2bdadc54bc
Create Date: 2026-02-28 10:22:37.287672
"""
from alembic import op
import sqlalchemy as sa


revision = '3bab8cc55439'
down_revision = '8d2bdadc54bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_transfer_request',
    sa.Column('requesting_user_id', sa.String(length=36), nullable=False),
    sa.Column('from_chapter_id', sa.String(length=36), nullable=False),
    sa.Column('to_chapter_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('from_chapter_approved_by', sa.String(length=36), nullable=True),
    sa.Column('from_chapter_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('to_chapter_approved_by', sa.String(length=36), nullable=True),
    sa.Column('to_chapter_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('denied_by', sa.String(length=36), nullable=True),
    sa.Column('denied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['denied_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['from_chapter_approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['from_chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_chapter_approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_chapter_id'], ['chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_transfer_request_from_chapter_id'), 'chapter_transfer_request', ['from_chapter_id'], unique=False)
    op.create_index(op.f('ix_chapter_transfer_request_requesting_user_id'), 'chapter_transfer_request', ['requesting_user_id'], unique=False)
    op.create_index(op.f('ix_chapter_transfer_request_status'), 'chapter_transfer_request', ['status'], unique=False)
    op.create_index(op.f('ix_chapter_transfer_request_to_chapter_id'), 'chapter_transfer_request', ['to_chapter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapter_transfer_request_to_chapter_id'), table_name='chapter_transfer_request')
    op.drop_index(op.f('ix_chapter_transfer_request_status'), table_name='chapter_transfer_request')
    op.drop_index(op.f('ix_chapter_transfer_request_requesting_user_id'), table_name='chapter_transfer_request')
    op.drop_index(op.f('ix_chapter_transfer_request_from_chapter_id'), table_name='chapter_transfer_request')
    op.drop_table('chapter_transfer_request')
    # ### end Alembic commands ###
