"""Add notification model

Revision ID: 8d2bdadc54bc
Revises: 3c793e2299d7
Create Date: 2026-02-25 20:16:15.973721
"""
from alembic import op
import sqlalchemy as sa


revision = '8d2bdadc54bc'
down_revision = '3c793e2299d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_chapter_id'), 'notification', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_notification_recipient_id'), 'notification', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_recipient_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_chapter_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
