"""add config columns to organization chapter membership and payment

Revision ID: 9459e6600a20
Revises: f63be1edbc74
Create Date: 2026-02-16 15:08:15.250589
"""
from alembic import op
import sqlalchemy as sa


revision = '9459e6600a20'
down_revision = 'f63be1edbc74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('config', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('chapter_membership', sa.Column('custom_fields', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('organization', sa.Column('config', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('payment', sa.Column('fee_type_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'fee_type_id')
    op.drop_column('organization', 'config')
    op.drop_column('chapter_membership', 'custom_fields')
    op.drop_column('chapter', 'config')
    # ### end Alembic commands ###
