"""add_region_and_region_membership

Revision ID: b7d64c5b0e59
Revises: 9459e6600a20
Create Date: 2026-02-17 10:52:49.893956
"""
import uuid

from alembic import op
import sqlalchemy as sa


revision = 'b7d64c5b0e59'
down_revision = '9459e6600a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False, server_default='{}'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_org_region_name')
    )
    op.create_index(op.f('ix_region_organization_id'), 'region', ['organization_id'], unique=False)
    op.create_table('region_membership',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'region_id', name='uq_user_region')
    )
    op.create_index(op.f('ix_region_membership_region_id'), 'region_membership', ['region_id'], unique=False)
    op.create_index(op.f('ix_region_membership_user_id'), 'region_membership', ['user_id'], unique=False)
    op.add_column('chapter', sa.Column('region_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_chapter_region_id'), 'chapter', ['region_id'], unique=False)
    op.create_foreign_key(None, 'chapter', 'region', ['region_id'], ['id'])
    # ### end Alembic commands ###

    # Data backfill: create a "Default Region" for each existing org
    # and assign all its chapters to that region
    connection = op.get_bind()
    orgs = connection.execute(sa.text("SELECT id FROM organization")).fetchall()
    for org in orgs:
        region_id = str(uuid.uuid4())
        connection.execute(
            sa.text(
                "INSERT INTO region (id, organization_id, name, active, config, created_at, updated_at) "
                "VALUES (:id, :org_id, :name, true, '{}', NOW(), NOW())"
            ),
            {"id": region_id, "org_id": org.id, "name": "Default Region"},
        )
        connection.execute(
            sa.text("UPDATE chapter SET region_id = :region_id WHERE organization_id = :org_id"),
            {"region_id": region_id, "org_id": org.id},
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.drop_index(op.f('ix_chapter_region_id'), table_name='chapter')
    op.drop_column('chapter', 'region_id')
    op.drop_index(op.f('ix_region_membership_user_id'), table_name='region_membership')
    op.drop_index(op.f('ix_region_membership_region_id'), table_name='region_membership')
    op.drop_table('region_membership')
    op.drop_index(op.f('ix_region_organization_id'), table_name='region')
    op.drop_table('region')
    # ### end Alembic commands ###
