"""add organization_membership table

Revision ID: baa7d737e920
Revises: b7d64c5b0e59
Create Date: 2026-02-17 11:32:39.075663
"""
from alembic import op
import sqlalchemy as sa


revision = 'baa7d737e920'
down_revision = 'b7d64c5b0e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_membership',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_organization')
    )
    op.create_index(op.f('ix_organization_membership_organization_id'), 'organization_membership', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_membership_user_id'), 'organization_membership', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_membership_user_id'), table_name='organization_membership')
    op.drop_index(op.f('ix_organization_membership_organization_id'), table_name='organization_membership')
    op.drop_table('organization_membership')
    # ### end Alembic commands ###
