"""add mfa_reset_event audit table

Revision ID: cbdffd5a4544
Revises: f72df32199c6
Create Date: 2026-04-27 14:08:00.909063
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'cbdffd5a4544'
down_revision = 'f72df32199c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_reset_event',
    sa.Column('target_user_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('actor_role_at_reset', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfa_reset_event_actor_user_id'), 'mfa_reset_event', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_mfa_reset_event_target_user_id'), 'mfa_reset_event', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mfa_reset_event_target_user_id'), table_name='mfa_reset_event')
    op.drop_index(op.f('ix_mfa_reset_event_actor_user_id'), table_name='mfa_reset_event')
    op.drop_table('mfa_reset_event')
    # ### end Alembic commands ###
