"""Add Event and EventAttendance models

Revision ID: d1ee397b2a3f
Revises: 3bab8cc55439
Create Date: 2026-03-01 19:53:42.561631
"""
from alembic import op
import sqlalchemy as sa


revision = 'd1ee397b2a3f'
down_revision = '3bab8cc55439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('public_slug', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('service_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('banner_image_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_chapter_id'), 'events', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_events_public_slug'), 'events', ['public_slug'], unique=True)
    op.create_table('event_attendance',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('attendee_name', sa.String(length=200), nullable=True),
    sa.Column('attendee_email', sa.String(length=255), nullable=True),
    sa.Column('rsvp_status', sa.String(length=20), nullable=False),
    sa.Column('checked_in', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=200), nullable=True),
    sa.Column('ticket_price_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_user_attendance'),
    sa.UniqueConstraint('stripe_session_id')
    )
    op.create_index(op.f('ix_event_attendance_chapter_id'), 'event_attendance', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_event_attendance_event_id'), 'event_attendance', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_attendance_user_id'), 'event_attendance', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_attendance_user_id'), table_name='event_attendance')
    op.drop_index(op.f('ix_event_attendance_event_id'), table_name='event_attendance')
    op.drop_index(op.f('ix_event_attendance_chapter_id'), table_name='event_attendance')
    op.drop_table('event_attendance')
    op.drop_index(op.f('ix_events_public_slug'), table_name='events')
    op.drop_index(op.f('ix_events_chapter_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
